(() => {
"use strict";
const PRODUCTS_KEY="inventoryProducts",SHOPS_KEY="inventoryShops";
let products=loadProducts(),shops=loadShops();
const $=id=>document.getElementById(id);
function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2)}
function loadProducts(){try{const x=JSON.parse(localStorage.getItem(PRODUCTS_KEY)||"[]");return Array.isArray(x)?x.map(p=>({id:p.id||id(),name:String(p.name||""),category:p.category||"食品",stock:Number(p.stock)||0,minimumStock:Number(p.minimumStock)||0,shops:Array.isArray(p.shops)?p.shops:(p.shop?[p.shop]:[]),purchaseHistory:Array.isArray(p.purchaseHistory)?p.purchaseHistory.slice(0,5):[]})):[]}catch(e){return[]}}
function loadShops(){try{const x=JSON.parse(localStorage.getItem(SHOPS_KEY)||'["スーパー","ドラッグストア","Amazon"]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function save(){localStorage.setItem(PRODUCTS_KEY,JSON.stringify(products));localStorage.setItem(SHOPS_KEY,JSON.stringify(shops))}
function esc(x){const d=document.createElement("div");d.textContent=String(x);return d.innerHTML}
function tab(t){document.querySelectorAll(".tab-button").forEach(b=>b.classList.toggle("active",b.dataset.tab===t));document.querySelectorAll(".tab-content").forEach(s=>s.classList.toggle("active",s.id===t));render()}
function renderChecks(){const b=$("shopCheckboxes");b.innerHTML="";if(!shops.length){b.innerHTML='<p class="help-text">「その他」から買う場所を登録してください。</p>';return}shops.forEach(s=>{const l=document.createElement("label");l.className="checkbox-item";const i=document.createElement("input");i.type="checkbox";i.value=s;const sp=document.createElement("span");sp.textContent=s;l.append(i,sp);b.append(l)})}
function renderShops(){const b=$("shopMasterList");b.innerHTML="";if(!shops.length){b.innerHTML='<div class="empty-message">買う場所がありません。</div>';return}shops.forEach((s,i)=>{const r=document.createElement("div");r.className="shop-master-item";const n=document.createElement("span");n.textContent=s;const d=document.createElement("button");d.className="shop-master-delete";d.textContent="削除";d.dataset.shopIndex=i;r.append(n,d);b.append(r)})}
function renderInventory(){const b=$("inventoryList"),c=$("categoryFilter").value,q=$("searchInput").value.trim().toLowerCase();let a=products.filter(p=>(c==="すべて"||p.category===c)&&p.name.toLowerCase().includes(q));b.innerHTML="";if(!a.length){b.innerHTML='<div class="empty-message">商品がありません。</div>';return}a.sort((x,y)=>x.name.localeCompare(y.name,"ja"));a.forEach(p=>{const card=document.createElement("div");card.className="product-card";card.innerHTML='<div class="product-name">'+esc(p.name)+'</div><div class="category">'+esc(p.category)+'</div>';const area=document.createElement("div");area.className="stock-area";area.innerHTML='<button class="stock-button" data-action="minus">−</button><div class="stock-number">'+p.stock+'</div><button class="stock-button" data-action="plus">＋</button>';area.querySelectorAll("button").forEach(x=>x.dataset.id=p.id);card.append(area);if(p.stock<=p.minimumStock){const low=document.createElement("div");low.className="low-stock";low.textContent="要補充";card.append(low)}const st=document.createElement("div");st.className="help-text";st.textContent="買う場所";card.append(st);const tags=document.createElement("div");tags.className="shop-tags";p.shops.forEach(s=>{const t=document.createElement("span");t.className="shop-tag";t.textContent=s;tags.append(t)});card.append(tags);const mi=document.createElement("div");mi.textContent="最低在庫："+p.minimumStock;card.append(mi);const acts=document.createElement("div");acts.className="product-actions";const det=document.createElement("button");det.className="small-button";det.textContent="詳細・購入";det.dataset.action="detail";det.dataset.id=p.id;const del=document.createElement("button");del.className="small-button delete-button";del.textContent="削除";del.dataset.action="delete";del.dataset.id=p.id;acts.append(det,del);card.append(acts);b.append(card)})}
function renderShopping(){const b=$("shoppingList");b.innerHTML="";const groups={};products.filter(p=>p.stock<=p.minimumStock).forEach(p=>p.shops.forEach(s=>(groups[s]??=[]).push(p)));if(!Object.keys(groups).length){b.innerHTML='<div class="empty-message">買うものはありません。</div>';return}Object.entries(groups).forEach(([s,a])=>{const g=document.createElement("div");g.className="shopping-group";const h=document.createElement("h3");h.textContent=s;g.append(h);a.forEach(p=>{const item=document.createElement("div");item.className="shopping-item";const row=document.createElement("div");row.className="shopping-item-header";const info=document.createElement("div");info.innerHTML="<strong>"+esc(p.name)+"</strong><br>現在庫："+p.stock;const btn=document.createElement("button");btn.className="buy-button";btn.textContent="買った";btn.dataset.action="detail";btn.dataset.id=p.id;row.append(info,btn);item.append(row);g.append(item)});b.append(g)})}
function render(){renderInventory();renderShopping();renderChecks();renderShops()}
function detail(pid){const p=products.find(x=>x.id===pid);if(!p)return;const b=$("modalBody");b.innerHTML="";const h=document.createElement("h2");h.textContent=p.name;const info=document.createElement("p");info.textContent=`現在庫：${p.stock}　最低在庫：${p.minimumStock}`;const sh=document.createElement("p");sh.textContent="買う場所";const tags=document.createElement("div");tags.className="shop-tags";p.shops.forEach(s=>{const t=document.createElement("span");t.className="shop-tag";t.textContent=s;tags.append(t)});const title=document.createElement("h3");title.textContent="購入記録";const lab=document.createElement("label");lab.textContent="購入数";const inp=document.createElement("input");inp.type="number";inp.min=1;inp.value=1;inp.id="purchaseQuantity";lab.append(inp);const buy=document.createElement("button");buy.className="primary-button";buy.textContent="購入した";buy.dataset.action="purchase";buy.dataset.id=pid;const ht=document.createElement("h3");ht.textContent="購入履歴（直近5回）";const his=document.createElement("div");his.className="history";if(!p.purchaseHistory.length)his.textContent="購入履歴はありません。";else p.purchaseHistory.forEach(x=>{const r=document.createElement("div");r.className="history-item";r.textContent=`${x.date}：${x.quantity}個`;his.append(r)});b.append(h,info,sh,tags,title,lab,buy,ht,his);$("modal").classList.remove("hidden")}
function purchase(pid){const p=products.find(x=>x.id===pid),n=Number($("purchaseQuantity").value);if(!p||!Number.isInteger(n)||n<=0){alert("1以上の購入数を入力してください。");return}p.stock+=n;const d=new Date(),date=`${d.getFullYear()}/${String(d.getMonth()+1).padStart(2,"0")}/${String(d.getDate()).padStart(2,"0")}`;p.purchaseHistory.unshift({date,quantity:n});p.purchaseHistory=p.purchaseHistory.slice(0,5);save();closeModal();render()}
function changeStock(pid,n){const p=products.find(x=>x.id===pid);if(!p)return;p.stock=Math.max(0,p.stock+n);save();render()}
function closeModal(){$("modal").classList.add("hidden")}
document.addEventListener("click",e=>{const t=e.target.closest(".tab-button");if(t){tab(t.dataset.tab);return}const a=e.target.closest("[data-action]");if(a){const idv=a.dataset.id;if(a.dataset.action==="minus")changeStock(idv,-1);if(a.dataset.action==="plus")changeStock(idv,1);if(a.dataset.action==="detail")detail(idv);if(a.dataset.action==="delete"){const p=products.find(x=>x.id===idv);if(p&&confirm("「"+p.name+"」を削除しますか？")){products=products.filter(x=>x.id!==idv);save();render()}}if(a.dataset.action==="purchase")purchase(idv)}})
$("closeModal").addEventListener("click",closeModal);$("modal").addEventListener("click",e=>{if(e.target===$("modal"))closeModal()});
$("categoryFilter").addEventListener("change",renderInventory);$("searchInput").addEventListener("input",renderInventory);
$("productForm").addEventListener("submit",e=>{e.preventDefault();const name=$("productName").value.trim(),shopsSelected=[...document.querySelectorAll("#shopCheckboxes input:checked")].map(x=>x.value);if(!name)return alert("商品名を入力してください。");if(!shopsSelected.length)return alert("買う場所を1つ以上選択してください。");products.push({id:id(),name,category:$("category").value,stock:Math.max(0,Number($("stock").value)||0),minimumStock:Math.max(0,Number($("minimumStock").value)||0),shops:shopsSelected,purchaseHistory:[]});save();e.target.reset();$("stock").value=0;$("minimumStock").value=1;alert("商品を登録しました。");tab("inventory")});
$("shopForm").addEventListener("submit",e=>{e.preventDefault();const n=$("shopName").value.trim();if(!n)return;if(shops.includes(n))return alert("同じ買う場所がすでに登録されています。");shops.push(n);save();$("shopName").value="";render()});
$("shopMasterList").addEventListener("click",e=>{const b=e.target.closest("[data-shop-index]");if(!b)return;const i=Number(b.dataset.shopIndex),s=shops[i];if(products.some(p=>p.shops.includes(s)))return alert("この買う場所を使用している商品があります。先に商品から外してください。");if(confirm("「"+s+"」を削除しますか？")){shops.splice(i,1);save();render()}});
$("backupButton").addEventListener("click",()=>{const data={appName:"在庫管理",version:3,exportedAt:new Date().toISOString(),products,shops},blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a"),d=new Date();a.href=url;a.download=`在庫管理_バックアップ_${d.getFullYear()}${String(d.getMonth()+1).padStart(2,"0")}${String(d.getDate()).padStart(2,"0")}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)});
$("restoreButton").addEventListener("click",()=>$("restoreFile").click());$("restoreFile").addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=x=>{try{const d=JSON.parse(x.target.result);if(!Array.isArray(d.products)||!Array.isArray(d.shops))throw Error();if(!confirm("現在のデータをバックアップで置き換えます。よろしいですか？"))return;products=d.products.map(p=>({id:p.id||id(),name:String(p.name||""),category:p.category||"食品",stock:Number(p.stock)||0,minimumStock:Number(p.minimumStock)||0,shops:Array.isArray(p.shops)?p.shops:(p.shop?[p.shop]:[]),purchaseHistory:Array.isArray(p.purchaseHistory)?p.purchaseHistory.slice(0,5):[]}));shops=[...new Set(d.shops.filter(s=>typeof s==="string"))];save();render();alert("バックアップから復元しました。")}catch(err){alert("バックアップファイルを読み込めませんでした。")}finally{e.target.value=""}};r.readAsText(f,"UTF-8")});
render();
})();